openapi: 3.0.0
info:
  version: 1.0.0
  title: Hello World Exec v1
  description: hello world exec v1
servers:
  - url: /hello/world/bundle.v1/
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello World Exec V1 Endpoints
paths:
  /welcome:
    post:
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-kgrid-artifact:
        type: String
        value: main.js
      x-kgrid-adapterType:
        type: String
        value: JAVASCRIPT
      x-kgrid-entry:
        type: String
        value: welcome
components:
  schemas:
    user:
      required:
        - name
      properties:
        name:
          type: string
          example: Bob
    welcomeOutput:
      required:
        - result
      properties:
        result:
          type: string
          example: welcome
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
