openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Minimum Viable Object Service'
  description: 'A service that receives a JSON object and returns the same JSON object'
servers:
  - url: '/mvo/kgrid/v0.0.1/'
    description: TBD
tags:
  - name: KO Endpoints
    description: Minimum Viable Object Service Endpoints
paths:
  /echo:
    post:
      description: Echo the input as the output result
      operationId: echo
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/echoOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    user:
      required:
        - inputs
      properties:
        name:
          type: string
          example: '{"key1":"value1","key2":"value2"}'
    welcomeOutput:
      required:
        - result
      properties:
        result:
          type: string
          example: '{"food":"pizza","drink":"lemonade"}'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
